# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Sf49bWel46N+OSm4DvxHORRQCNiPYb41/6h6+Vdr6PkBq8ofRC6XW/tJ53s8yU1QARHA+CmGGkDuSKKX5fwUkkoo37SiaJtPeu6QL0UzrBqCOcMBS5Mltu1MUv9q9jJhxqt4ptoZlCT8JrYTi+uF6Vhk8AqCIRHI9Gmw9Zvrfrd5UaOgFdSYfMdB6SxhVD1N9AwAZ4zvJu7nIqAqPlTwfYCzmxapjPW6WxyIir6a06p9A5SAoXVfCdAQ/DFFzt5QzOY3K2VRWJLkvicXZ1YJ17ZBXwLjwXF9xly7EYRl6xzNGBn33m2BvgyDN89TmFL/vOpwty7mrMwFZUjcnseGsAyxPIqchh+HVyitvK05VNDCeWAG3QqCw3cNO5gvOWKnbLXsCFk4hCsWnWYxsjydlXMcA7uvsAuPKYMHd40+ruYXoZTevLjDXs2+j9Y+DYm9P/SZHUUTGuAulCVBr+l4K/ZpDvuGbIZJXBQ3/iphFHesa0pKoo5Q9Q1NrZTeNb8o1Q4BQzVWlpQ5buOL/k2SiLu/QfX53rod+KbnI8TTWDBu0HBN9F3zahJI/zkY2Yb970HQNFS3SpxJT8whdvzfHDedUSiWb0E5kwPhXroKygsR+zkPfqkL8oMfxEy2ebZghulELm/ht1bxrc4T0xqaiwkGLYqHIfCH3ws8w3BzAes="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml